development:
  adapter: postgresql
  database: db/development
  pool: 5

test:
  adapter: postgresql
  database: db/test
  pool: 5

production:
  adapter: psotgresql
  database: db/production
  pool: 5
